config/routes.rb
Rails.application.routes.draw do
  resources :musicians
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/musician.rb
class Musician < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/musicians_controller.rb
class MusiciansController < ApplicationController
  before_action :set_musician, only: [:show, :edit, :update, :destroy]

  # GET /musicians
  # GET /musicians.json
  def index
    @musicians = Musician.all
  end

  # GET /musicians/1
  # GET /musicians/1.json
  def show
  end

  # GET /musicians/new
  def new
    @musician = Musician.new
  end

  # GET /musicians/1/edit
  def edit
  end

  # POST /musicians
  # POST /musicians.json
  def create
    @musician = Musician.new(musician_params)

    respond_to do |format|
      if @musician.save
        format.html { redirect_to @musician, notice: 'Musician was successfully created.' }
        format.json { render :show, status: :created, location: @musician }
      else
        format.html { render :new }
        format.json { render json: @musician.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /musicians/1
  # PATCH/PUT /musicians/1.json
  def update
    respond_to do |format|
      if @musician.update(musician_params)
        format.html { redirect_to @musician, notice: 'Musician was successfully updated.' }
        format.json { render :show, status: :ok, location: @musician }
      else
        format.html { render :edit }
        format.json { render json: @musician.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /musicians/1
  # DELETE /musicians/1.json
  def destroy
    @musician.destroy
    respond_to do |format|
      format.html { redirect_to musicians_url, notice: 'Musician was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_musician
      @musician = Musician.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def musician_params
      params.require(:musician).permit(:name, :instrument)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/musicians_helper.rb
module MusiciansHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Band</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/musicians/_form.html.erb
<%= form_for(musician) do |f| %>
  <% if musician.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(musician.errors.count, "error") %> prohibited this musician from being saved:</h2>

      <ul>
      <% musician.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :instrument %>
    <%= f.text_field :instrument %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/musicians/edit.html.erb
<h1>Editing Musician</h1>

<%= render 'form', musician: @musician %>

<%= link_to 'Show', @musician %> |
<%= link_to 'Back', musicians_path %>

app/views/musicians/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Musicians</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Instrument</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @musicians.each do |musician| %>
      <tr>
        <td><%= musician.name %></td>
        <td><%= musician.instrument %></td>
        <td><%= link_to 'Show', musician %></td>
        <td><%= link_to 'Edit', edit_musician_path(musician) %></td>
        <td><%= link_to 'Destroy', musician, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Musician', new_musician_path %>

app/views/musicians/new.html.erb
<h1>New Musician</h1>

<%= render 'form', musician: @musician %>

<%= link_to 'Back', musicians_path %>

app/views/musicians/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @musician.name %>
</p>

<p>
  <strong>Instrument:</strong>
  <%= @musician.instrument %>
</p>

<%= link_to 'Edit', edit_musician_path(@musician) %> |
<%= link_to 'Back', musicians_path %>